<?php
declare(strict_types=1);
require dirname(__DIR__) . '/app/core/bootstrap.php'; require_role('admin');
$model=new Computer($pdo); $users=(new User($pdo))->all(); $departments=(new Department($pdo))->all(); $id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT); $existing=$id?$model->find($id):null; if($id&&!$existing){http_response_code(404);exit('Computer not found.');}
$values=$existing?:['asset_tag'=>'','brand'=>'','model'=>'','serial_number'=>'','operating_system'=>'','ip_address'=>'','department_id'=>'','user_id'=>'','status'=>'functional','purchase_date'=>'']; $errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 $values=['asset_tag'=>post_text('asset_tag'),'brand'=>post_text('brand'),'model'=>post_text('model'),'serial_number'=>post_text('serial_number'),'operating_system'=>post_text('operating_system'),'ip_address'=>post_text('ip_address'),'department_id'=>post_text('department_id'),'user_id'=>post_text('user_id'),'status'=>post_text('status'),'purchase_date'=>post_text('purchase_date')];
 if(!verify_csrf_token($_POST['csrf_token']??null))$errors[]='Invalid form token.'; if($values['asset_tag']===''||strlen($values['asset_tag'])>50)$errors[]='Asset tag is required and must be 50 characters or fewer.'; if($model->assetExists($values['asset_tag'],$id?:null))$errors[]='That asset tag is already in use.'; if(!valid_enum($values['status'],['functional','maintenance','broken','retired']))$errors[]='Invalid computer status.'; if($values['department_id']!==''&&!(new Department($pdo))->exists((int)$values['department_id']))$errors[]='Invalid department.'; if($values['user_id']!==''&&!(new User($pdo))->find((int)$values['user_id']))$errors[]='Invalid assigned user.'; if($values['purchase_date']!==''&&!valid_date_value($values['purchase_date'],'Y-m-d'))$errors[]='Invalid purchase date.';
 if(!$errors){$data=['asset_tag'=>$values['asset_tag'],'brand'=>$values['brand']?:null,'model'=>$values['model']?:null,'serial_number'=>$values['serial_number']?:null,'operating_system'=>$values['operating_system']?:null,'ip_address'=>$values['ip_address']?:null,'department_id'=>$values['department_id']!==''?(int)$values['department_id']:null,'user_id'=>$values['user_id']!==''?(int)$values['user_id']:null,'status'=>$values['status'],'purchase_date'=>$values['purchase_date']?:null];if($id)$model->update($id,$data);else$model->create($data);flash('message',$id?'Computer updated.':'Computer created.');redirect('admin_computers.php');}
}
require dirname(__DIR__).'/app/views/layout.php'; page_header($id?'Edit computer':'Add computer');
?><div class="toolbar"><div><p class="eyebrow">Administration / inventory</p><h1><?= $id?'Edit computer':'Add computer' ?></h1></div><a href="admin_computers.php">Back to computers</a></div><?php foreach($errors as $error):?><p class="error"><?=e($error)?></p><?php endforeach;?><section class="panel form-panel"><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="grid"><p><label>Asset tag</label><input name="asset_tag" maxlength="50" value="<?=e($values['asset_tag'])?>" required></p><p><label>Brand</label><input name="brand" value="<?=e($values['brand'])?>"></p><p><label>Model</label><input name="model" value="<?=e($values['model'])?>"></p><p><label>Serial number</label><input name="serial_number" value="<?=e($values['serial_number'])?>"></p><p><label>Operating system</label><input name="operating_system" value="<?=e($values['operating_system'])?>"></p><p><label>IP address</label><input name="ip_address" value="<?=e($values['ip_address'])?>"></p><p><label>Department</label><select name="department_id"><option value="">None</option><?php foreach($departments as $department):?><option value="<?= (int)$department['id'] ?>" <?= (string)$values['department_id']===(string)$department['id']?'selected':'' ?>><?=e($department['name'])?></option><?php endforeach;?></select></p><p><label>Assigned user</label><select name="user_id"><option value="">Unassigned</option><?php foreach($users as $user):?><option value="<?= (int)$user['id'] ?>" <?= (string)$values['user_id']===(string)$user['id']?'selected':'' ?>><?=e($user['first_name'].' '.$user['last_name'])?></option><?php endforeach;?></select></p><p><label>Status</label><select name="status"><?php foreach(['functional','maintenance','broken','retired'] as $status):?><option <?= $values['status']===$status?'selected':'' ?>><?=e($status)?></option><?php endforeach;?></select></p><p><label>Purchase date</label><input name="purchase_date" type="date" value="<?=e($values['purchase_date'])?>"></p></div><button type="submit">Save computer</button></form></section><?php page_footer(); ?>