<?php

declare(strict_types=1);

require dirname(__DIR__) . '/app/core/bootstrap.php';

require_authentication();
$user = current_user();
$ticketModel = new Ticket($pdo);
$role = $user['role'];
$counts = $role === 'admin' ? $ticketModel->countAll() : $ticketModel->countForUser((int) $user['id'], $role);
$total = array_sum($counts);
$activeTotal = $counts['open'] + $counts['assigned'] + $counts['in_progress'];
$computerTotal = $role === 'admin' ? (new Computer($pdo))->countAll() : 0;
$printerTotal = $role === 'admin' ? (new Printer($pdo))->countAll() : 0;
$recentTickets = $role === 'admin' ? $ticketModel->recentActivity() : [];
$technicianTickets = $role === 'technician' ? $ticketModel->forTechnician((int) $user['id']) : [];
$notifications = (new TicketActivity($pdo))->unread((int) $user['id']);
require dirname(__DIR__) . '/app/views/layout.php';
page_header('Dashboard');
?>
<section class="dashboard-hero"><div><p class="eyebrow"><?= e(ucfirst($role)) ?> workspace</p><h1>Good to see you, <?= e($user['first_name']) ?>.</h1><p class="hero-copy"><?php if ($role === 'admin'): ?>Keep the service desk moving with a clear view of every request.<?php elseif ($role === 'technician'): ?>Your assigned work, intervention notes, and priorities in one place.<?php else: ?>Report an issue and follow its progress from start to finish.<?php endif; ?></p></div><div class="hero-mark" aria-hidden="true"><span></span><span></span><span></span><span></span></div></section>
<?php if ($role === 'technician'): ?><section class="metric-grid technician-metrics" aria-label="My ticket summary"><div class="metric-card"><span class="metric-label">My tickets</span><strong><?= $total ?></strong><span class="metric-caption">Assigned to me</span></div><div class="metric-card metric-assigned"><span class="metric-label">To start</span><strong><?= $counts['assigned'] ?></strong><span class="metric-caption">Ready for work</span></div><div class="metric-card metric-progress"><span class="metric-label">In progress</span><strong><?= $counts['in_progress'] ?></strong><span class="metric-caption">Being worked on</span></div><div class="metric-card metric-resolved"><span class="metric-label">Completed</span><strong><?= $counts['resolved'] + $counts['closed'] ?></strong><span class="metric-caption">Work finished</span></div></section><?php else: ?><section class="metric-grid" aria-label="Ticket summary"><div class="metric-card"><span class="metric-label">All tickets</span><strong><?= $total ?></strong><span class="metric-caption">Current workload</span></div><div class="metric-card metric-open"><span class="metric-label">Open</span><strong><?= $activeTotal ?></strong><span class="metric-caption">Active tickets</span></div><div class="metric-card metric-assigned"><span class="metric-label">Assigned</span><strong><?= $counts['assigned'] ?></strong><span class="metric-caption">With a technician</span></div><div class="metric-card metric-progress"><span class="metric-label">In progress</span><strong><?= $counts['in_progress'] ?></strong><span class="metric-caption">Being worked on</span></div><div class="metric-card metric-resolved"><span class="metric-label">Resolved</span><strong><?= $counts['resolved'] ?></strong><span class="metric-caption">Ready for review</span></div></section><?php endif; ?>
<?php if ($role === 'admin'): ?><section class="inventory-summary" aria-label="Device inventory"><div class="inventory-heading"><p class="eyebrow">Device inventory</p><h2>Equipment in the system</h2><p class="muted">A quick view of the devices currently tracked.</p></div><div class="inventory-count inventory-computers"><div class="device-card-heading"><span class="device-icon device-icon-computer" aria-hidden="true">PC</span><span class="metric-label">Computers</span></div><strong><?= $computerTotal ?></strong><span class="metric-caption">Registered devices</span></div><div class="inventory-count inventory-printers"><div class="device-card-heading"><span class="device-icon device-icon-printer" aria-hidden="true">PR</span><span class="metric-label">Printers</span></div><strong><?= $printerTotal ?></strong><span class="metric-caption">Registered devices</span></div></section><?php endif; ?>
<?php if ($role === 'admin'): ?><section class="panel activity-panel"><div class="section-heading"><div><p class="eyebrow">Live overview</p><h2>Recent ticket activity</h2></div><a href="admin_tickets.php">Manage all tickets</a></div><div class="activity-table"><table><tr><th>ID</th><th>Ticket</th><th>Requester</th><th>Technician</th><th>Status</th><th>Last change</th></tr><?php foreach ($recentTickets as $recentTicket): ?><tr><td><a href="ticket.php?id=<?= (int) $recentTicket['id'] ?>">#<?= (int) $recentTicket['id'] ?></a></td><td><a href="ticket.php?id=<?= (int) $recentTicket['id'] ?>"><?= e($recentTicket['title']) ?></a></td><td><?= e($recentTicket['requester_name']) ?></td><td><?= e($recentTicket['technician_name'] ?? 'Not assigned') ?></td><td><span class="activity-status status-<?= e($recentTicket['status']) ?>"><?= e(str_replace('_', ' ', $recentTicket['status'])) ?></span></td><td><?= e($recentTicket['updated_at']) ?></td></tr><?php endforeach; ?></table></div></section><?php endif; ?>
<?php if ($role === 'technician'): ?><section class="panel activity-panel"><div class="section-heading"><div><p class="eyebrow">Work queue</p><h2>Choose a ticket to work on</h2></div><a href="technician_tickets.php">Open full queue</a></div><div class="activity-table"><table><tr><th>ID</th><th>Ticket</th><th>Requester</th><th>Status</th><th>Next action</th></tr><?php foreach ($technicianTickets as $technicianTicket): ?><tr><td>#<?= (int) $technicianTicket['id'] ?></td><td><?= e($technicianTicket['title']) ?></td><td><?= e($technicianTicket['requester']) ?></td><td><span class="activity-status status-<?= e($technicianTicket['status']) ?>"><?= e(str_replace('_', ' ', $technicianTicket['status'])) ?></span></td><td><?php if ($technicianTicket['status'] === 'assigned'): ?><a href="ticket.php?id=<?= (int) $technicianTicket['id'] ?>">Start work</a><?php elseif ($technicianTicket['status'] === 'in_progress'): ?><a href="maintenance.php?ticket_id=<?= (int) $technicianTicket['id'] ?>">Complete report</a><?php else: ?><a href="ticket.php?id=<?= (int) $technicianTicket['id'] ?>">View details</a><?php endif; ?></td></tr><?php endforeach; ?></table></div></section><?php endif; ?>
<?php if ($notifications): ?><section class="panel notifications-panel"><div class="section-heading"><div><p class="eyebrow">Notifications</p><h2>Recent updates</h2></div></div><?php foreach ($notifications as $notification): ?><p><a href="<?= $notification['ticket_id'] ? 'ticket.php?id=' . (int) $notification['ticket_id'] : '#' ?>"><?= e($notification['message']) ?></a> <span class="muted"><?= e($notification['created_at']) ?></span></p><?php endforeach; ?></section><?php endif; ?>
<section class="dashboard-columns"><div class="panel action-panel"><p class="eyebrow">Quick actions</p><h2>What would you like to do?</h2><?php if ($role === 'employee'): ?><a class="action-link" href="tickets.php"><span class="action-icon">+</span><span><b>Create or view tickets</b><small>Tell the service desk what needs attention.</small></span><span>-&gt;</span></a><?php elseif ($role === 'technician'): ?><a class="action-link" href="technician_tickets.php"><span class="action-icon">#</span><span><b>View assigned tickets</b><small>Pick up your next intervention.</small></span><span>-&gt;</span></a><?php else: ?><a class="action-link" href="admin_tickets.php"><span class="action-icon">#</span><span><b>Manage tickets</b><small>Assign, filter, and review requests.</small></span><span>-&gt;</span></a><a class="action-link" href="admin_users.php"><span class="action-icon">@</span><span><b>Review users</b><small>See the people using the service desk.</small></span><span>-&gt;</span></a><?php endif; ?></div><div class="panel status-panel"><p class="eyebrow">Workflow</p><h2>Ticket lifecycle</h2><div class="workflow"><span class="workflow-step active">Open</span><i></i><span class="workflow-step">Assigned</span><i></i><span class="workflow-step">In progress</span><i></i><span class="workflow-step">Resolved</span><i></i><span class="workflow-step">Closed</span></div><p class="muted">Stay informed as each request moves through the service desk.</p></div></section>
<?php page_footer(); ?>